server:
  port: 8086
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/congee
    username: root
    password: 123
    driverClassName: com.mysql.jdbc.Driver
    tomcat:
      max-active: 20
      min-idle: 8
      initial-size: 10
      max-wait: 60000
      max-idle: 8
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    show-sql: true
    database: MYSQL
mybatis:

  type-aliases-package: com.congee.mall.mapper
#  mapper-locations: classpath*:com/congee/mall/mapper/*.xml
  config-location: classpath:mybatis-config.xml